model_reasoning_effort = "medium"
network_access = true
approval_policy = "on-request"
sandbox_mode    = "workspace-write"

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]

[mcp_servers.playwright]
type = "stdio"
command = "npx"
args = ["@playwright/mcp@latest"]

[tui]
notifications = true

[features]
rmcp_client = true
web_search_request = true

[sandbox_workspace_write]
network_access = true
