model = "gpt-5-codex"
model_reasoning_effort = "medium"
network_access = true
approval_policy = "on-request"
sandbox_mode    = "workspace-write"

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]

[mcp_servers.playwright]
type = "stdio"
command = "npx"
args = ["@playwright/mcp@latest"]

[mcp_servers.todoist]
command = "npx"
args = ["-y", "mcp-remote", "https://ai.todoist.net/mcp"]

[mcp_servers.linear]
command = "npx"
args = ["-y", "mcp-remote", "https://mcp.linear.app/mcp"]
startup_timeout_sec = 100

[tui]
notifications = true

[features]
rmcp_client = true
web_search_request = true

[sandbox_workspace_write]
network_access = true
